/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pikas (https://sketchfab.com/Pikas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-torri-gate-fc6d1bee39574ddf83408dec3c6724eb
Title: Japanese Torri Gate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gate(props) {
  const { nodes, materials } = useGLTF('/japanese_torri_gate.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2.5, 0, -0.3]} scale={20}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torri_Gate_Torri_gate_0.geometry}
            material={materials.Torri_gate}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Torri_Gate_Rope&Gold_0'].geometry}
            material={materials.RopeGold}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/japanese_torri_gate.glb')
