/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: yochan.176 (https://sketchfab.com/yochan.176)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-archive-weapon-sorasaki-hina-70ad8f728ede4aada830ab7250b23648
Title: [Blue Archive Weapon] - Sorasaki Hina
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gun(props) {
  const { nodes, materials } = useGLTF('/hina.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 1, 0.1, 0.11]} scale={500}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials['Default_OBJ.002']}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hina.glb')
